export const GET_AUTHORIZATION_REQUEST: 'GET_AUTHORIZATION_REQUEST' = 'GET_AUTHORIZATION_REQUEST';
export const GET_AUTHORIZATION_SUCCESS: 'GET_AUTHORIZATION_SUCCESS' = 'GET_AUTHORIZATION_SUCCESS';
export const GET_AUTHORIZATION_ERROR: 'GET_AUTHORIZATION_ERROR' = 'GET_AUTHORIZATION_ERROR';

export const GET_LOGOUT_REQUEST: 'GET_LOGOUT_REQUEST' = 'GET_LOGOUT_REQUEST';
export const GET_LOGOUT_SUCCESS: 'GET_LOGOUT_SUCCESS' = 'GET_LOGOUT_SUCCESS';
export const GET_LOGOUT_ERROR: 'GET_LOGOUT_ERROR' = 'GET_LOGOUT_ERROR';

export const ADD_CONTACT_REQUEST: 'ADD_CONTACT_REQUEST' = 'ADD_CONTACT_REQUEST';
export const ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS' = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_ERROR: 'ADD_CONTACT_ERROR' = 'ADD_CONTACT_ERROR';

export const GET_ALL_CONTACTS_REQUEST: 'GET_ALL_CONTACTS_REQUEST' = 'GET_ALL_CONTACTS_REQUEST';
export const GET_ALL_CONTACTS_SUCCESS: 'GET_ALL_CONTACTS_SUCCESS' = 'GET_ALL_CONTACTS_SUCCESS';
export const GET_ALL_CONTACTS_ERROR: 'GET_ALL_CONTACTS_ERROR' = 'GET_ALL_CONTACTS_ERROR';

export const DELETE_CONTACT_REQUEST: 'DELETE_CONTACT_REQUEST' = 'DELETE_CONTACT_REQUEST';
export const DELETE_CONTACT_SUCCESS: 'DELETE_CONTACT_SUCCESS' = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_ERROR: 'DELETE_CONTACT_ERROR' = 'DELETE_CONTACT_ERROR';

export const EDIT_CONTACT_REQUEST: 'EDIT_CONTACT_REQUEST' = 'EDIT_CONTACT_REQUEST';
export const EDIT_CONTACT_SUCCESS: 'EDIT_CONTACT_SUCCESS' = 'EDIT_CONTACT_SUCCESS';
export const EDIT_CONTACT_ERROR: 'EDIT_CONTACT_ERROR' = 'EDIT_CONTACT_ERROR';

export default function checkResponse(res: Response) {
    if (!res.ok) {
        throw new Error("Сервер не отвечает.");
    }
    return res.json();
}